.github/workflows/maven.yml
README.md

- added auto build check on push and pull_request (using GitHub Actions)

Setup auto build on push and PR (GitHub actions)

---

.github/CODEOWNERS
.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/custom.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
.github/SECURITY.md
README.md

Add github settings and templates

---

.github/workflows/codeql.yml
README.md

Add LGTM, Language grade, CodeQL analysis and  corresponding badges
Fixes #7
Result (badges) you can see [here](https://github.com/Samsung/LPVS)
* Java: v11

Add LGTM, Language grade, CodeQL badges

---

.github/dependabot.yml

To automate the search for 3rd party component updates, the dependabot configuration has been added
Every month will automatically create PRs for component updates
* Java: v11

Implement dependabot configuration

---

pom.xml

Fix for the dependabot tickets #12, #13, #14, #15, which were generated automatically.
Fixes #12, #13, #14, #15
java -jar target/lpvs-1.0.0.jar
* Java: v11

Close tickets #12, #13, #14, #15 with one combined fix

---

pom.xml
src/main/java/com/lpvs/entity/config/WebhookConfig.java
src/test/java/com/lpvs/entity/config/WebhookConfigTest.java

Added first unit test set (4 pcs) for the WebhookConfig class. This step is required for the GitHub action infra setup.
* Java: v11

Initial unit test for WebhookConfig class

---

src/main/java/com/lpvs/LicensePreValidationSystem.java
src/main/java/com/lpvs/controller/GitHubWebhooksController.java
src/main/java/com/lpvs/entity/LPVSFile.java
src/main/java/com/lpvs/entity/LPVSLicense.java
src/main/java/com/lpvs/entity/ResponseWrapper.java
src/main/java/com/lpvs/entity/config/WebhookConfig.java
src/main/java/com/lpvs/entity/enums/PullRequestAction.java
src/main/java/com/lpvs/service/DetectService.java
src/main/java/com/lpvs/service/GitHubService.java
src/main/java/com/lpvs/service/LicenseService.java
src/main/java/com/lpvs/service/QueueProcessorService.java
src/main/java/com/lpvs/service/QueueService.java
src/main/java/com/lpvs/service/scanner/scanoss/ScanossDetectService.java
src/main/java/com/lpvs/util/FileUtil.java
src/main/java/com/lpvs/util/WebhookUtil.java
src/test/java/com/lpvs/entity/config/WebhookConfigTest.java

Added missing copyright header into unit test file

Added missing copyright header

---

src/main/java/com/lpvs/service/scanner/scanoss/ScanossDetectService.java

Fix LGTM alerts

---

src/main/java/com/lpvs/entity/LPVSLicense.java
src/test/java/com/lpvs/entity/LPVSLicenseTest.java

Added unit test set for the LPVSLicense class. This step is required for the GitHub action infra setup.
* Java: v18

add tests for entity/LPVSLicense

---

src/test/java/com/lpvs/entity/enums/PullRequestActionTest.java

Added unit test set (2 pcs) for the `com.lpvs.entity.enums.PullRequestAction` class. This step is required for the GitHub action infra setup.
mvn test
* Java: v18

Tests for `entity.enums.PullRequestAction`

---

src/main/java/com/lpvs/LicensePreValidationSystem.java
src/test/java/com/lpvs/LicensePreValidationSystemTest.java

Added unit test set for the `LicensePreValidationSystem` class. This step is required for the GitHub action infra setup.
mvn test
* Java: v18

tests for `LicensePreValidationSystem`

---

src/test/java/com/lpvs/util/WebHookUtilTest.java

Added unit test set for the `com.lpvs.util.WebhookUtil` class. This step is required for the GitHub action infra setup.
mvn test
* Java: v18

Tests for `util.WebhookUtil`

---

src/test/java/com/lpvs/entity/LPVSFileTest.java

Add tests for LPVSFile class
* Java: v11

add test for LPVSFile

---

.github/workflows/test-suite.yml
pom.xml

The need to automate the testing process during PR
Fixes #17 
Check [github actions](https://github.com/Samsung/LPVS/actions)
* Java: v11

Add test-suite to github-actions workflow

---

src/main/java/com/lpvs/service/QueueProcessorService.java
src/main/java/com/lpvs/service/QueueService.java
src/test/java/com/lpvs/service/QueueProcessorServiceTest.java

Added unit test set for the `com.lpvs.service.QueueProcessorService` class. This step is required for the GitHub action infra setup.
mvn test
* Java: v18

Tests for `com.lpvs.service.QueueProcessorService`

---

src/main/java/com/lpvs/entity/LPVSFile.java
src/main/java/com/lpvs/service/QueueService.java
src/test/java/com/lpvs/service/QueueServiceTest.java

Added unit test set for the `com.lpvs.service.QueueService` class. This step is required for the GitHub action infra setup.
mvn test
* Java: v18

Tests for `com.lpvs.service.QueueService`

---

src/main/java/com/lpvs/controller/GitHubWebhooksController.java
src/test/java/com/lpvs/controller/GitHubWebhooksControllerTest.java

Test coverge for GitHubWebhookController
* Java: v11

GitHub webhooks controller test

---

src/test/java/com/lpvs/service/QueueProcessorServiceTest.java
src/test/java/com/lpvs/service/QueueServiceTest.java

Added missing copyright headers into unit test files.

Added missing copyright headers

---

pom.xml

A plugin is added to monitor warnings and fix them
```
mvn -B package --file pom.xml
```
Result:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] 
[INFO] …
```

Add a plugin to enable the show of warnings and deprecated methods

---

doc/testing_policy.md

For a better understanding of how to test a project, a testing policy is added.

Add test policy

---

pom.xml
src/main/java/com/lpvs/controller/GitHubWebhooksController.java
src/main/java/com/lpvs/entity/ResponseWrapper.java
src/main/java/com/lpvs/service/LicenseService.java
src/main/java/com/lpvs/service/scanner/scanoss/ScanossDetectService.java
src/test/java/com/lpvs/controller/GitHubWebhooksControllerTest.java
src/test/java/com/lpvs/service/QueueServiceTest.java

Reduce the number of warnings according to the test policy.
The current number of warnings is 0.
```
$ mvn clean install 
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ lpvs ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 15 source files to D:\Git\GitHub\LPVS\target\classes
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ lpvs ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.10.1:testCompile (default-testCompile) @ lpvs ---
[INFO] Changes detected - recompiling the …
```

Reduce the number of warnings according to the test policy

---

doc/lpvs-api.yaml

Add a description of the external LPVS API

Add external LPVS API description

---

src/main/java/com/lpvs/service/GitHubService.java
src/test/java/com/lpvs/service/GitHubServiceTest.java

Added unit test set for the com.lpvs.service.GithubService class. This step is required for the GitHub action infra setup.
mvn test
* Java: v18

`GithubService:: getPullRequestFiles() setPendingCheck() setErrorCheck()` tests

---

src/main/java/com/lpvs/service/LicenseService.java

Possible mistake with "license_name+" search. Please check if my fix is correct
mvn test
* Java: v18

`LicenseService::checkLicense()` bugfix

---

src/main/java/com/lpvs/service/LicenseService.java

Mistake with indexes corrected.
mvn test
* Java: v18

`LicenseService::findConflicts()` bugfix

---

pom.xml
src/main/java/com/lpvs/controller/GitHubWebhooksController.java
src/test/java/com/lpvs/controller/GitHubWebhooksControllerTest.java

Add more unit tests for GitHubWebhooksController 
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```
* Java: v11

Add GitHubWebhooksController unit tests

---

src/test/java/com/lpvs/service/GitHubServiceTest.java
src/test/java/com/lpvs/service/LicenseServiceTest.java

Added unit test set for the `com.lpvs.service.LicenseService` class. This step is required for the GitHub action infra setup.
Wait for 2 bugfix PRs, then test set will pass
mvn test
* Java: v18

`LicenseService`, 5 methods tests

---

Dockerfile
README.md
pom.xml

This PR will contain all changes required for the LPVS release v1.0.1.
Fixes #51 

Preparation of the release v1.0.1

---

.github/workflows/scorecard.yml
README.md

Adding OSSF scorecard to the README file

Add OSSF scorecard

---

.github/CODEOWNERS

Signed-off-by: Taewan Kim <t25.kim@samsung.com>
CODEOWNERS is updated according to my username change.

Change t25kim to tiokim

---

docker-compose.yml

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Addressing the vulnerability report from the community member.
- Masking the root password for the sample SQL DB access.
* Java: v11

Masking the key for addressing the vulnerability

---

.github/Docker_Usage.md
README.md
docker-compose.yml
src/main/java/com/lpvs/repository/LPVSLicenseConflictRepository.java
src/main/java/com/lpvs/repository/LPVSLicenseRepository.java
src/main/java/com/lpvs/repository/LPVSQueueRepository.java
src/main/java/com/lpvs/service/LPVSQueueService.java
src/main/resources/application.properties
src/main/resources/database_dump.sql

PR includes the fix for DB dump file and corresponding changes into the source code of repositories
Fixes #159 

fix: Updated DB dump and fixed SQL queries

---

.github/CONTRIBUTING.md
.github/SECURITY.md
README.md
src/main/java/com/lpvs/controller/GitHubWebhooksController.java

The project documentation and build instructions have been updated, and Javadoc has been added for the controller.

fix: rewrite LPVS documentation and add Javadoc comments to controller

---

src/main/java/com/lpvs/entity/LPVSPullRequest.java
src/test/java/com/lpvs/entity/LPVSPullRequestFilesUrlResponseTest.java
src/test/java/com/lpvs/entity/LPVSPullRequestTest.java

Improvement of the code coverage by unit tests.
Added tests for LPVSPullRequest and LPVSPullRequestFilesUrlResponse entities.

feat: add unit tests for LPVSPullRequest entity

---

src/main/java/com/lpvs/LicensePreValidationSystem.java
src/main/java/com/lpvs/controller/GitHubWebhooksController.java
src/main/java/com/lpvs/entity/LPVSDiffFile.java
src/main/java/com/lpvs/entity/LPVSFile.java
src/main/java/com/lpvs/entity/enums/LPVSPullRequestAction.java
src/main/java/com/lpvs/service/LPVSGitHubService.java
src/main/java/com/lpvs/service/LPVSLicenseService.java
src/main/java/com/lpvs/service/scanner/scanoss/LPVSScanossDetectService.java
src/main/java/com/lpvs/util/LPVSCommentUtil.java
src/main/java/com/lpvs/util/LPVSExitHandler.java
src/main/java/com/lpvs/util/LPVSFileUtil.java
src/main/java/com/lpvs/util/LPVSWebhookUtil.java
src/test/java/com/lpvs/LicensePreValidationSystemTest.java
src/test/java/com/lpvs/controller/GitHubWebhooksControllerTest.java
src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java
src/test/java/com/lpvs/service/LPVSLicenseServiceTest.java
src/test/java/com/lpvs/util/FileUtilTest.java

This pull request aims to create a reusable package, promoting code modularity and easier integration across projects.
Synchronize open-source and internal LPVS versions, ensuring consistency and improved collaboration between the two environments.
Deploy and test localy. 
* Java: v11

Sync with internal repo

---

src/main/java/com/lpvs/exception/ErrorResponse.java
src/main/java/com/lpvs/exception/LoginFailedException.java
src/test/java/com/lpvs/exception/ErrorResponseTest.java
src/test/java/com/lpvs/exception/LoginFailedExceptionTest.java
src/test/java/com/lpvs/exception/PageControllerAdviceTest.java
src/test/java/com/lpvs/exception/WrongAccessExceptionTest.java

In this PR `exception` classes are covered by additional unit tests.

feat: Add unit tests for `exception` classes

---

src/main/java/com/lpvs/service/LPVSQueueService.java
src/test/java/com/lpvs/service/LPVSLoginCheckServiceTest.java
src/test/java/com/lpvs/service/LPVSQueueServiceTest.java
src/test/java/com/lpvs/service/LPVSStatisticsServiceTest.java

In this PR, services are covered by additional unit tests.

feat: Add unit tests for services

---

.github/SECURITY.md
.github/workflows/CODE_OF_CONDUCT.md

Update security doc

---

src/main/java/com/lpvs/service/scanner/scanoss/LPVSScanossDetectService.java
src/test/java/com/lpvs/service/scanner/scanoss/LPVSScanossDetectServiceTest.java

In this PR, test for LPVSScanossDetectServicea is fixed.

fix: Fix unit test for LPVSScanossDetectService

---

src/test/java/com/lpvs/service/LPVSStatisticsServiceTest.java

Improve coverage for LPVSStatisticsService class, test getDashboardEntity() method.
Fixes # ([issue](https://github.com/Samsung/LPVS/issues/236))
1. Run tests: `mvn test`, observe status;
2. Run coverage report generation and observe imporvement 
* Java: v11

Update tests for LPVSStatisticsService class, increase coverage

---

pom.xml

Prepare POM file for new release candidate.
1. Run application: `mvn clean install`
* Java: v11

New release candidate

---

src/test/java/com/lpvs/config/SecurityConfigTest.java

In this PR, new config class is covered by an additional unit test.

feat: Add unit test for configuration class

---

src/test/java/com/lpvs/service/scanner/scanoss/LPVSScanossDetectServiceTest.java

Improve coverage for LPVSScanossDetectService class.

feat: Add unit test for LPVSScanossDetectService

---

src/main/java/com/lpvs/repository/LPVSLicenseConflictRepository.java
src/main/java/com/lpvs/repository/LPVSLicenseRepository.java

Fix to follow one style for all repositories in LPVS.

fix: Change CrudRepository to JpaRepository for 2 repos

---

pom.xml

Change LPVS version to preparation to the release v1.2.0

Preparation to the release v1.2.0

---

README.md

Fix for OpenSSF Best Practice badge URL

fix: Update OpenSSF Best Practice badge URL

---

.github/workflows/publish-docker-img.yml
.github/workflows/publish-jar.yml
.github/workflows/test-suite.yml

Fix security  issues: "Token-Permissions"

fix: Update github->actions workflow

---

doc/code-review-requirements.md

docs: Add code review requirements description

---

.github/workflows/build.yml
.github/workflows/findbugs.yml
.github/workflows/test-suite.yml
src/main/java/com/lpvs/service/LPVSLicenseService.java
src/main/java/com/lpvs/service/LPVSStatisticsService.java
src/main/java/com/lpvs/service/scanner/scanoss/LPVSScanossDetectService.java
src/main/java/com/lpvs/util/LPVSCommentUtil.java
src/main/java/com/lpvs/util/LPVSExitHandler.java
src/main/java/com/lpvs/util/LPVSFileUtil.java
src/test/java/com/lpvs/config/SecurityConfigTest.java
src/test/java/com/lpvs/entity/LPVSFileTest.java
src/test/java/com/lpvs/entity/LPVSPullRequestTest.java
src/test/java/com/lpvs/entity/LPVSQueueTest.java
src/test/java/com/lpvs/entity/LPVSResponseWrapperTest.java
src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java
src/test/java/com/lpvs/service/LPVSLicenseServiceTest.java
src/test/java/com/lpvs/service/LPVSLoginCheckServiceTest.java
src/test/java/com/lpvs/service/LPVSQueueServiceTest.java
src/test/java/com/lpvs/service/LPVSStatisticsServiceTest.java
src/test/java/com/lpvs/service/scanner/scanoss/LPVSScanossDetectServiceTest.java
src/test/java/com/lpvs/util/LPVSCommentUtilTest.java
src/test/java/com/lpvs/util/LPVSExitHandlerTest.java
src/test/java/com/lpvs/util/LPVSFileUtilTest.java
src/test/java/com/lpvs/util/LPVSWebhookUtilTest.java
src/test/resources/A_B.json

To improve the code coverage to 90%, we have to add more unit tests.
Fixes #298 

feat: Add more unit tests to improve coverage

---

.github/workflows/javadoc.yml

fix permissions for github->action

fix: Update github->action javadoc permissions

---

.github/workflows/javadoc.yml

Need to add a permission to be able to create a branch
* Java: v11

fix: Add context write permission to javadoc.yml

---

doc/overview.html
src/main/java/com/lpvs/config/SecurityConfig.java
src/main/java/com/lpvs/config/package-info.java
src/main/java/com/lpvs/entity/result/LPVSResult.java
src/main/java/com/lpvs/entity/result/LPVSResultFile.java
src/main/java/com/lpvs/entity/result/LPVSResultInfo.java
src/main/java/com/lpvs/exception/ErrorResponse.java
src/main/java/com/lpvs/exception/LoginFailedException.java
src/main/java/com/lpvs/exception/PageControllerAdvice.java
src/main/java/com/lpvs/exception/WrongAccessException.java
src/main/java/com/lpvs/exception/package-info.java
src/main/java/com/lpvs/repository/LPVSDetectedLicenseRepository.java
src/main/java/com/lpvs/repository/LPVSLicenseConflictRepository.java
src/main/java/com/lpvs/repository/LPVSLicenseRepository.java
src/main/java/com/lpvs/repository/LPVSMemberRepository.java
src/main/java/com/lpvs/repository/LPVSPullRequestRepository.java
src/main/java/com/lpvs/repository/LPVSQueueRepository.java
src/main/java/com/lpvs/repository/package-info.java
src/main/java/com/lpvs/util/LPVSCommentUtil.java
src/main/java/com/lpvs/util/LPVSExitHandler.java
src/main/java/com/lpvs/util/LPVSFileUtil.java
src/main/java/com/lpvs/util/LPVSTableConfiguration.java
src/main/java/com/lpvs/util/LPVSWebhookUtil.java
src/main/java/com/lpvs/util/package-info.java

This PR is related to #307 and covers config, exception, repository and unit packages.

docs: Add Javadoc comments for config, exception, repository and unit

---

pom.xml

Update of `pom.xml` file for providing reproducible builds.
Fixes #316 

fix: Provide reproducible builds

---

src/main/java/com/lpvs/LicensePreValidationSystem.java
src/main/java/com/lpvs/controller/GitHubWebhooksController.java
src/main/java/com/lpvs/controller/LPVSWebController.java
src/main/java/com/lpvs/util/LPVSWebhookUtil.java
src/test/java/com/lpvs/controller/LPVSWebControllerTest.java
src/test/java/com/lpvs/util/LPVSWebhookUtilTest.java

To improve the security of LPVS, we've applied hardening mechanisms according to task #317 
Fixes #317

fix: Apply hardening mechanisms to controller endpoints

---

.github/CONTRIBUTING.md
doc/lpvs-api.yaml
pom.xml
src/main/java/com/lpvs/controller/GitHubWebhooksController.java

Updated YAML file with API. Validated at https://jsonformatter.org/yaml-validator
Also, PR includes minor fixes in the documentation.
Fixes #318 

docs: Update of YAML file with newly added endpoints

---

.github/workflows/create-release.yml

Adding automatic generation of releases, uploading of release artifacts, etc
After push any tag "v*" see to Release
* Java: v11

feat: Adding automatic release generation

---

Dockerfile

Fixed an error that occurred when publishing a docker image

fix: Fix Dockerfile for secure installation of scanoss package

---

src/test/java/com/lpvs/service/LPVSDetectServiceTest.java

Added test cases for LPVSDetectService in order to improve branch coverage.
* Java: v11

test: Improve LPVSDetectService branch coverage

---

README.md

Update some links in Readme file:
- removed repo size (unnecessary block)
- updated DOI link

docs: Updated links in Readme file

---

README.md

Update steps in Quick Start part of the guide in README file

docs: update guide in Quick Start part of README.md file

---

.github/CONTRIBUTING.md

Add the next types:
```
refactor="Code Refactoring"
perf="Performance Improvements"
build="Builds"
ci="Continuous Integration"
revert="Reverts"
```
The result you can see during the automatic creation of the release change log.
* Java: v11
* LPVS Release: v1.3x

docs: Expand the types of commit names

---

pom.xml

Update the package version 1.3.0 -> 1.4.0 for the release

chore: Update package version to 1.4.0

---

Dockerfile

Spring 2.7 has been replaced with 3.2, therefore we update the docker container as well.
Fixes #351

build: Update JDK11 to JDK17 in Dockerfile

---

.github/SECURITY.md
frontend/package-lock.json
frontend/package.json

Remove frontend package vulnerabilities: CVE-2021-3803, CVE-2023-44270
* Java: v17
* LPVS Release: v1.4.x
* Google Chrome: 120.0.6099.217

fix: Remove packages vulnerabilities in frontend

---

README.md

External projects can use the package, so instruction have been created on how to do this

docs: Add guide how to use lpvs-x.y.z.jar in other project

---

README.md
doc/quick-start-guide-and-build.md

`README.md` is too long. Need to divide into logical parts and create separate *.md file

docs: Reorganize README.md

---

pom.xml

Release v1.4.1 of LPVS with JDK 17 and synchronize code with internal module.

chore: Update package version to 1.4.1

---

.github/workflows/publish-release.yml

To successfully publish artifacts need to update JDK11 to JDK17
* Java: v17

fix: Update JDK11 to JDK17 in .github/workflows/publish-release.yml

---

pom.xml

Add possibility to reuse class from external LPVS through external JAR dependency
* Java: v17

chore: add plugin to build executable JAR

---

doc/quick-start-guide-and-build.md
src/main/java/com/lpvs/entity/LPVSLicense.java
src/main/java/com/lpvs/repository/LPVSLicenseRepository.java
src/main/resources/database_dump.sql

Fix for changing table name to avoid the issue because of name conflicts.
* Java: v17

fix: Change table name to avoid name conflicts

---

.github/workflows/build.yml
.github/workflows/check-docker.yml
.github/workflows/codeql.yml
.github/workflows/findbugs.yml
.github/workflows/java-format-checker.yml
.github/workflows/publish-release.yml
.github/workflows/scorecards.yml
.github/workflows/test-suite.yml

1. Add comment with version to each used actions
2. Add names for some same steps
3. Update harder/runner action version in check-docker workflow

chore: refactor and update github action workflows

---

src/main/java/com/lpvs/service/LPVSQueueService.java

fix: Fix incorrect log message

---

docker-compose.yml
pom.xml

Change the version of LPVS to 1.4.2.

chore: change version to 1.4.2

---

pom.xml

Revert "build(deps): bump org.apache.maven.plugins:maven-assembly-plugin from 3.6.0 to 3.7.1"

---

src/main/java/com/lpvs/entity/LPVSFile.java
src/main/java/com/lpvs/service/scan/LPVSDetectService.java
src/main/resources/database_dump.sql
src/test/java/com/lpvs/entity/LPVSFileTest.java
src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java
src/test/java/com/lpvs/service/LPVSLicenseServiceTest.java
src/test/java/com/lpvs/service/LPVSQueueServiceTest.java
src/test/java/com/lpvs/service/scan/LPVSDetectServiceTest.java
src/test/java/com/lpvs/service/scan/scanner/LPVSScanossDetectServiceTest.java
src/test/resources/convert1.txt

Current PR includes extension of the LPVS File class and contains a new method for converting byte ranges returned from the scanner to the number of lines in the file.

feat: Add conversion of the byte range in file to file lines

---

src/main/java/com/lpvs/controller/GitHubController.java
src/main/java/com/lpvs/service/scan/LPVSDetectService.java
src/main/java/com/lpvs/service/scan/scanner/LPVSScanossDetectService.java
src/main/java/com/lpvs/util/LPVSFileUtil.java
src/test/java/com/lpvs/service/scan/LPVSDetectServiceTest.java
src/test/java/com/lpvs/util/LPVSFileUtilTest.java

Current PR fixes the issue with incorrect file separators in scan results.
* Java: v17
* LPVS Release: v1.4.2

fix: Resolve an issue with incorrect file separators

---

pom.xml
src/main/java/com/lpvs/entity/LPVSFile.java
src/test/java/com/lpvs/entity/LPVSFileTest.java

Current PR contains fixes for Svace defects.
* Java: v17
* LPVS Release: v1.4.2

fix: Fix Svace defects and update unit tests

---

src/main/java/com/lpvs/service/LPVSGitHubService.java
src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java

PR contains a fix for the incorrect link displayed on the commit message when provided with the hub link.
* Java: v17
* LPVS Release: v1.4.3

fix: Missing link to the scan results in case of hub link present

---

pom.xml
src/main/java/com/lpvs/service/LPVSQueueService.java

PR contains changes to version 1.5.0 and fixes of log typos.

chore: Change version to v1.5.0

---

src/main/java/com/lpvs/repository/LPVSLicenseRepository.java
src/main/java/com/lpvs/service/LPVSLicenseService.java
src/main/java/com/lpvs/util/LPVSWebhookUtil.java
src/main/resources/database_dump.sql
src/test/java/com/lpvs/service/LPVSLicenseServiceTest.java
src/test/java/com/lpvs/util/LPVSWebhookUtilTest.java

Current PR contains:
- fix for the license search by alternative names
- extension of the test DB dump with license alternative names
- removed code duplicates according to the SAM tool check
* Java: v17
* LPVS Release: v1.5.0

fix: Fix license search by alternative names and remove code duplicates

---

.clusterfuzzlite/Dockerfile
pom.xml

Remove hardcoded dependencies from POM file. Be default, the latest supported version of plugins will be used.
Also, we decided to use apache-maven-3.9.6 (the latest stable version).
* Java: v17
* LPVS Release: v1.5.0

build: Remove hardcoded dependencies from POM file

---

src/main/java/com/lpvs/LicensePreValidationService.java
src/test/java/com/lpvs/LicensePreValidationServiceTest.java

Improve code coverage for "main" function of the LPVS service. 
* Java: v17
* LPVS Release: v1.5.1

test: Add unit tests for "main" function

---

src/main/java/com/lpvs/service/scan/scanner/LPVSScanossDetectService.java
src/test/resources/A_B.json

While executing functional tests, the next error was detected:
```
27-06-2024 07:28:44.440 [main] INFO  com.lpvs.service.LPVSQueueProcessorService.queueProcessor - PROCESS Webhook id = 3
27-06-2024 07:28:44.441 [LPVS::6] INFO  com.lpvs.service.LPVSQueueService.processWebHook - Processing webhook ID: 3, attempt: 1 for PR: https://github.sec.samsung.net/SOSHUB/LPVS-test/pull/1753
27-06-2024 07:28:47.715 [LPVS::6] ERROR com.lpvs.service.LPVSQueueService.processWebHook - Can't authorize commentResults() com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 1859 path $.url_stats.
See https://github.com/google/gson/blob/main/Troubleshooting.md#malformed-json
```
Reason: incorrect processing of "url_stats" field in Json.
Current PR is fixing this issue.
Also, I removed …

fix: Fix incorrect processing of Json, remove unused fields

---

pom.xml

Release v1.5.2 of the LPVS project.

chore: Change version to v1.5.2

---

src/main/resources/application-singlescan.properties

Current PR fixes runtime errors and warnings in a single scan scenario.
AS-IS:
TO-BE:
It is provided in the description.

fix: Add missing property to remove run errors

---

.github/workflows/publish-documentation.yml
.github/workflows/publish-release.yml

Update job "Generate and Publish MkDocs" with migration from Javadoc to MkDocs

ci: update documentation management job with MkDocs

---

.github/SECURITY.md

Specify the installation of an additional extension for the correct display of the documentation
* Java: v17

fix: Update Security guide

---

pom.xml

chore: Change version to 2.0.0 for release

---

src/main/java/com/lpvs/repository/LPVSPullRequestRepository.java

Current PR contains the fix of MySQL query.
It was tested by a functional test set.

fix: Change query to database to avoid the runtime error

---

pom.xml

Change version of LPVS to 2.0.1.

chore: Change version to 2.0.1

---

src/main/java/com/lpvs/repository/LPVSDetectedLicenseRepository.java

This PR contains the extension of the queries supported by `LPVSDetectedLicenseRepository` class.
Local test passed.

chore: Extend the list of LPVSDetectedLicenseRepository queries

---

src/main/resources/templates/report_single_scan.html

PR contains fixes in the CSS styles used in single-scan HTML reports.

fix: Incorrect properties in the single scan report template

---

pom.xml

chore: Change version to 2.1.0

---

.github/PULL_REQUEST_TEMPLATE.md
pom.xml

Minor maintenance release with updated dependencies (monthly updates).

chore: Update version to 2.1.1

---

.github/CODEOWNERS

Add @t-naumenko to the list of code owners.

chore: Extend the list of maintainers

---

pom.xml

Minor maintenance release with updated dependencies and security vulnerabilities fix.

chore: Update version to 2.1.3

---

news.md

Test for license validation
- The added file does not relate to any function of this project.
- The added file is from other open source called OSORI under BSD-2 license.
Please include a summary of the change and which issue is fixed. Also, provide relevant motivation and context. List any dependencies that are required for this change.
This is orthogonal to any existing functions from LPVS. So no test is required for the successful run of this project itself.

[Test] Adding dummy file (from other open source)

---

.github/SECURITY.md
requirements.txt

Fix CVE-2024-5569 vulnerability by increasing 3rd party zipp python package

build(deps): Fix CVE-2024-5569 vulnerability

---

pom.xml

Minor maintenance release with updated dependencies.

chore: Update version to 2.1.4

---

src/main/java/com/lpvs/service/LPVSLicenseService.java
src/main/java/com/lpvs/util/LPVSPayloadUtil.java
src/test/java/com/lpvs/service/LPVSLicenseServiceTest.java
src/test/java/com/lpvs/util/LPVSPayloadUtilTest.java
src/test/resources/osori_db_response_internal.json
src/test/resources/osori_db_response_internal_no_traffic.json
src/test/resources/osori_db_response_internal_red.json
src/test/resources/osori_db_response_internal_yellow.json

OSORI response could have a different format based on the used OSORI DB server.
Provided an alternative parser for the OSORI response.
Tested locally. All UTs passed.

fix: Implement alternative parser of OSORI response
