README.md, src/main/java/com/lpvs/service/GitHubService.java
Signed-off-by: Taewan Kim <t25.kim@samsung.com>
If `github.token` is not set from the `application.properties`, `LPVS` look for the value from `LPVS_GITHUB_TOKEN` env variable. 
The user can run LPVS docker container with `LPVS_GITHUB_TOKEN` env variable like below.
```sh
docker run --rm -p 7896:7896 --name lpvs -e LPVS_GITHUB_TOKEN=<TOKEN> lpvs:latest
```
=> Set github token from the environment variable.

.github/workflows/build.yml, README.md
Add restrict permissions for GITHUB_TOKEN and pin actions to full length commit sha 
* Java: v11
=> Add protection for the github->action build workflow

README.md, src/main/java/com/lpvs/service/LicenseService.java, src/main/resources/application.properties
To run LPVS in Docker container, we need to provide the possibility to set the path to the `licenses.json` by the user (previously, the path was hardcoded). In current PR I make the path changeable. In further PRs I will provide the possibility to set the path as an environment variable (as well as token, login, etc.)
Also, I want to fix one of the LGTM issue from https://lgtm.com/projects/g/Samsung/LPVS/alerts/?mode=list (Class Conflict overrides equals but not hashCode)
All possible combinations of licenses.json paths were tested.
* Java: v11
=> Make file path to license.json changeable

pom.xml, src/main/java/com/lpvs/service/GitHubService.java, src/test/java/com/lpvs/service/GitHubServiceTest.java
Added unit test set (4 pcs) for the GithubService::getRepositoryLicense method. This step is required for the GitHub action infra setup.
Refactored creation of `GitHubService` in order to simplify unit testing.
New dependency:
`mockito-inline:4.7.0`
Needed for mock external library objects. `mockito-inline` instead of `mockito-core` is used, because only `mockito-inline` supports mocking static methods
* Java: v18
=> GithubService::getRepositoryLicense tests

README.md, pom.xml, src/main/java/com/lpvs/controller/GitHubWebhooksController.java, src/main/resources/application.properties, src/test/java/com/lpvs/controller/GitHubWebhooksControllerTest.java
Scanning will be carried out when github secret and lpvs secret are the same.
1. Add `github.secret` to the `application.properties` file like below.
```
github.secret=lpvs
```
2. Run LPVS
3. Check the LPVS log like below.
```
2022-08-31 16:48:31.188  INFO 71382 --- [nio-7896-exec-1] c.l.controller.GitHubWebhooksController  : lpvs   signature: 42c493a2e4062a2fb506083432e1e9208e44000acfd04971097ac62a1779a0d5
2022-08-31 16:48:31.188  INFO 71382 --- [nio-7896-exec-1] c.l.controller.GitHubWebhooksController  : github signature: 42c493a2e4062a2fb506083432e1e9208e44000acfd04971097ac62a1779a0d5
```
* Java: v11
=> Run scan logic if github secret and lpvs secret are the same

src/main/java/com/lpvs/service/DetectService.java, src/test/java/com/lpvs/entity/ResponseWrapperTest.java, src/test/java/com/lpvs/service/DetectServiceTest.java
Added unit test set for the `com.lpvs.service.DetectService` and `com.lpvs.entity.ResponseWrapper` classes. This step is required for the GitHub action infra setup.
mvn test
* Java: v18
=> `DetectService` and `ResponseWrapper` tests

src/main/java/com/lpvs/service/GitHubService.java, src/test/java/com/lpvs/service/GitHubServiceTest.java
Added unit test set for the com.lpvs.service.GithubService class. This step is required for the GitHub action infra setup.
mvn test
* Java: v18
=> GithubService:: `commentResults` and `getMatchedLinesAsLink` tests

.github/workflows/findbugs.yml, README.md, pom.xml, spotbugs-security-include.xml, src/main/java/com/lpvs/controller/GitHubWebhooksController.java
Added scenario to run FindBugs analysis.
Also added small fixes for README file.
=> Enable FindBugs analysis

src/test/java/com/lpvs/service/LicenseServiceTest.java
Signed-off-by: Taewan Kim <t25.kim@samsung.com>
The warning below is fixed.
```bash
[INFO] --- maven-compiler-plugin:3.10.1:testCompile (default-testCompile) @ lpvs ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 15 source files to /home/t25kim/work/LPVS/target/test-classes
[WARNING] /home/t25kim/work/LPVS/src/test/java/com/lpvs/service/LicenseServiceTest.java:[152,90] unchecked cast
required: java.util.List<com.lpvs.service.LicenseService.Conflict<java.lang.String,java.lang.String>>
found:    java.lang.Object
```
```
mvn test
```
* Java: v11
* LPVS Release: v1.0.1
=> Fix `unchecked cast` warning

README.md
Removed the LGTM badges as they are no longer supported from December 16th.
=> Remove lgtm badges

.github/workflows/publish.yml
Signed-off-by: Taewan Kim <t25.kim@samsung.com>
Currently, lpvs is only published with `latest` tag. 
This PR is to publish the image with the `specific tag` version as well as `latest`.
See the [example](https://github.com/tiokim/LPVS/pkgs/container/lpvs).
* Java: v11
* LPVS Release: v1.0.1
=> Publish the docker image with latest and tag version

docker-compose.yml
Duplicate Key : environment
Non-existent Key : WAIT_HOSTS
**Error log of the duplicate key, environment**
```
$ docker compose up
yaml: unmarshal errors:
line 13: mapping key "environment" already defined at line 6
```
**Error log of the non-existent key, WAIT_HOSTS**
```
$ docker compose up
yaml: line 11: did not find expected key
```
$ docker compose up
* Java: v11
* LPVS Release: v1.0.2
=> Fix the errors of duplicate and non-existent keys

src/main/java/com/lpvs/util/LPVSTableConfiguration.java, src/test/java/com/lpvs/util/LPVSTableConfigurationTest.java
Add an option to configure database tables for the open-source LPVS.
* Java: v11
=> Add table configuration class

pom.xml, src/main/java/com/lpvs/controller/GitHubWebhooksController.java, src/main/java/com/lpvs/service/LPVSGitHubService.java, src/main/resources/application.properties
Changed default configuration in application properties to prevent issues with Default launch:
- added table properties configuration;
- added default token (requred change in order to operate with real repo);
Fixes # (207)
* Java: v11
=> Modify default configuration file to prevent fails during LPVS service start

src/main/java/com/lpvs/service/LPVSGitHubService.java, src/main/java/com/lpvs/service/scanner/scanoss/LPVSScanossDetectService.java, src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java
Fix json parser in order to proceed with empty license array. 
Removed "null" string at the end of comment message in case if no Hub Link in webhook request.
Fixes # ([issue](https://github.com/Samsung/LPVS/issues/208))
* Java: v11
=> Fix missing comment on pull request

frontend/src/pages/Home.jsx, src/main/java/com/lpvs/auth/OAuthService.java, src/main/java/com/lpvs/entity/LPVSMember.java, src/main/java/com/lpvs/service/LPVSLoginCheckService.java
Fixed login error. **#209** 
Created PR  again due to incorrect commit.
- frontend
```
cd frontend
npm install
npm start
```
- backend
```
cd target
java -jar lpvs-*.jar
```
- Test image
* Java: v11
* LPVS Release: v1.1.0
=> Fix login error.

src/main/java/com/lpvs/entity/LPVSMember.java, src/main/java/com/lpvs/service/LPVSLoginCheckService.java, src/main/resources/database_dump.sql
Fixed login error backend part. **#209**, **#213**
Created PR  again due to incorrect commit.
Fixes #214 
- frontend
```
cd frontend
npm install
npm start
```
- backend
```
cd target
java -jar lpvs-*.jar
```
* Java: v11
* LPVS Release: v1.1.0
=> Fix duplicate DB when login (backend)

frontend/src/pages/Home.jsx
An error happens when a request to add the new member to db is called twice in a row due to StrictMode.
1. Run frontend server with `npm start` at frontend folder.
2. Open Chrome browser with DevTools and Go to http://localhost:3000.
3. See the network requests,`login/check`, from DevTools.
* Java: v11
* LPVS Release: v1.1.0
=> Add error handling code during login check

README.md
Adding a link to the high-level diagrams including module, library dependency and others (https://sourcespy.com/github/samsunglpvs/). Built directly from source and updated on schedule. Intended to simplify developer's introduction to the project. In the spirit of transparency - I am the author of the diagrams. Hope contributors find it useful.
No functionality impact. Documentation-only changes.
=> docs: add repository map reference to README.md

docker-compose.yml, src/main/java/com/lpvs/auth/OAuthAttributes.java
It is intended to login with Github or Github Enterprise account.
1. Creating an OAuth app from Github is required. see the [official doc](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app).
2. Place the necessary values to the properties, `client-id` and `client-secret`, in docker-compose.yml file.
3. Build with `docker compose build` and run the lpvs container with `docker compose up`
4. Go to `http://localhost:7896/login` on the web browser and choose `Github`.
* Java: v11
=> Add Github OAuth feature to backend application

frontend/src/App.jsx, frontend/src/pages/History.jsx, frontend/src/pages/Home.jsx, frontend/src/pages/User.jsx, src/main/java/com/lpvs/controller/LPVSWebController.java
Fixes #237 
1. Place the necessary values to the properties(such as `client-id`, `client-secret` and others) in docker-compose.yml file.
2. Build with `docker compose build` and run the lpvs container with `docker compose up`.
3. Go to http://localhost:7896 on the web browser.
4. Login and access other web pages.
* Java: v11
=> Change duplicate interfaces between backend and frontend

src/main/java/com/lpvs/entity/result/LPVSResult.java, src/main/java/com/lpvs/entity/result/LPVSResultInfo.java, src/test/java/com/lpvs/entity/results/LPVSResultFileTest.java, src/test/java/com/lpvs/entity/results/LPVSResultInfoTest.java, src/test/java/com/lpvs/entity/results/LPVSResultTest.java
In this PR `entity\result` classes are covered by additional unit tests.
=> feat: Add unit-tests for entity/result classes

.gitignore, src/test/java/com/lpvs/entity/LPVSDetectedLicenseTest.java, src/test/java/com/lpvs/entity/LPVSDiffFileTest.java, src/test/java/com/lpvs/entity/LPVSLoginMemberTest.java, src/test/java/com/lpvs/entity/LPVSMemberTest.java, src/test/java/com/lpvs/entity/enums/LPVSPullRequestActionTest.java, src/test/java/com/lpvs/entity/enums/LPVSPullRequestStatusTest.java, src/test/java/com/lpvs/entity/enums/LPVSVcsTest.java
In this PR, missing `entity` and `enum` classes are covered by additional unit tests.
=> feat: Add missing unit-tests for `entities` and `enums`

pom.xml
Implements change to pom.xml to build project in such a way so that class files are placed at the root of the JAR, which enables use of the built package as a dependency in other projects.
All unit tests were not touched and still pass.
* Java: v11
* LPVS Release: v1.1.0
=> Change to the pom.xml file to allow usage as a library

src/main/java/com/lpvs/entity/dashboard/DashBoardElements.java, src/main/java/com/lpvs/entity/dashboard/Dashboard.java, src/main/java/com/lpvs/entity/dashboard/DashboardElementsByDate.java, src/test/java/com/lpvs/entity/dashboard/DashBoardElementsTest.java, src/test/java/com/lpvs/entity/dashboard/DashboardElementsByDateTest.java, src/test/java/com/lpvs/entity/dashboard/DashboardTest.java, src/test/java/com/lpvs/entity/enums/GradeTest.java
In this PR, `dashboard` classes are covered by additional unit tests.
=> feat: Add missing unit tests for `dashboard` classes

src/test/java/com/lpvs/controller/LPVSWebControllerTest.java
In this PR, new controller classes are covered by additional unit tests.
=> feat: Add unit tests for controller

.github/workflows/java-format-checker.yml
You need to add a checker to match the style code
See github->actions
=> Add java format checker to github Actions

.github/dependabot.yml, .github/workflows/build.yml, .github/workflows/codeql.yml, .github/workflows/findbugs.yml, .github/workflows/java-format-checker.yml, .github/workflows/publish-gh-package.yml, .github/workflows/publish.yml, .github/workflows/scorecards.yml, .github/workflows/test-suite.yml, Dockerfile
Apply security best practices into workflows and Docker file. These changes are recommend by StepSecurity
=> Apply security best practices into workflows and Docker file

.github/workflows/test-suite.yml, README.md
Use Codecov to measure and display project coverage report.
=> fix: Update test-suite.yml for displaying the code coverage in correct format

frontend/package-lock.json, frontend/package.json, src/main/java/com/lpvs/service/LPVSGitHubService.java, src/main/java/com/lpvs/service/OAuthService.java, src/test/java/com/lpvs/service/OAuthServiceTest.java
Current PR removes unused frontend modules and fixes incorrect UT on backend.
=> fix: Remove unused frontend modules and fix incorrect UT on backend

.github/SECURITY.md
Fix for https://github.com/Samsung/LPVS/security/code-scanning/27
=> fix: Fix for "Security-Policy" warning about missing info in SECURITY.md

.github/workflows/javadoc.yml, doc/overview.html, pom.xml, src/main/java/com/lpvs/LicensePreValidationSystem.java, src/main/java/com/lpvs/controller/GitHubWebhooksController.java, src/main/java/com/lpvs/controller/LPVSWebController.java, src/main/java/com/lpvs/controller/package-info.java, src/main/java/com/lpvs/package-info.java, src/test/java/com/lpvs/controller/GitHubWebhooksControllerTest.java, src/test/java/com/lpvs/controller/LPVSWebControllerTest.java
Here I want to enable Javadoc generation and publication on Github pages.
In this PR I covered `com.lpvs` and `com.lpvs.controller` packages by comments. 
Other packages will be covered by Javadoc comments step-by-step in other PRs.
Also, I've created the task #307 with the request to update comments.
=> docs: Enable Javadoc generation as GitHub action

.github/workflows/javadoc.yml
Use actions-gh-pages for publication of Javadoc.
=> fix: Use actions-gh-pages for publication of Javadoc

.clusterfuzzlite/Dockerfile, .github/workflows/cflite_batch.yml
Fix Pinned-Dependencies of `gcr.io/oss-fuzz-base/base-builder-jvm` and `google/clusterfuzzlite/actions`
=> fix: Specifies the version of the components used in the clusterfuzzlite

Dockerfile
pip does not perform checks to protect against remote tampering. If add `--require-hashes` option, we can check the hash of the package being installed.
Fixes #321 
=> fix: Apply security install of python package into Dockerfile

src/main/java/com/lpvs/service/LPVSDetectService.java, src/main/java/com/lpvs/service/LPVSGitHubConnectionService.java, src/main/java/com/lpvs/service/LPVSGitHubService.java, src/main/java/com/lpvs/service/LPVSLicenseService.java, src/main/java/com/lpvs/service/LPVSLoginCheckService.java, src/main/java/com/lpvs/service/LPVSQueueProcessorService.java, src/main/java/com/lpvs/service/LPVSQueueService.java, src/main/java/com/lpvs/service/LPVSStatisticsService.java, src/main/java/com/lpvs/service/OAuthService.java, src/main/java/com/lpvs/service/package-info.java, src/main/java/com/lpvs/service/scanner/scanoss/LPVSScanossDetectService.java, src/main/java/com/lpvs/service/scanner/scanoss/package-info.java
Current PR contains final updates in Javadoc comments and covers all services.
Fixes #307
=> docs: Add Javadoc comments for services

src/main/java/com/lpvs/entity/auth/LPVSMember.java, src/main/java/com/lpvs/service/LPVSDetectService.java, src/main/java/com/lpvs/util/LPVSCommentUtil.java
Fix existing JavaDoc errors.
* Java: v11
=> fix: Fix existing javadoc comments

src/main/java/com/lpvs/service/LPVSGitHubService.java, src/main/java/com/lpvs/service/LPVSQueueService.java, src/main/java/com/lpvs/service/scanner/scanoss/LPVSScanossDetectService.java, src/main/java/com/lpvs/util/LPVSWebhookUtil.java, src/test/java/com/lpvs/service/LPVSDetectServiceTest.java, src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java, src/test/java/com/lpvs/service/LPVSQueueServiceTest.java, src/test/java/com/lpvs/service/scanner/scanoss/LPVSScanossDetectServiceTest.java, src/test/java/com/lpvs/util/LPVSWebhookUtilTest.java
Current pull request provides correct processing of exceptions in  `LPVSWebhookUtil` class. 
Also, it contains corresponding updates in unit tests. 
Fixes #301 
=> fix: Add `throw Exception` in case of error in `LPVSWebhookUtil` class

.github/workflows/build.yml, .github/workflows/codeql.yml, .github/workflows/findbugs.yml, .github/workflows/publish-release.yml, .github/workflows/test-suite.yml, README.md, pom.xml, src/main/java/com/lpvs/config/SecurityConfig.java, src/main/java/com/lpvs/controller/GitHubController.java, src/main/java/com/lpvs/entity/LPVSDetectedLicense.java, src/main/java/com/lpvs/entity/LPVSLicense.java, src/main/java/com/lpvs/entity/LPVSLicenseConflict.java, src/main/java/com/lpvs/entity/LPVSPullRequest.java, src/main/java/com/lpvs/entity/LPVSQueue.java, src/main/java/com/lpvs/entity/auth/LPVSMember.java, src/main/java/com/lpvs/service/LPVSDetectService.java, src/main/java/com/lpvs/service/LPVSGitHubConnectionService.java, src/main/java/com/lpvs/service/LPVSLicenseService.java, src/main/java/com/lpvs/service/LPVSQueueService.java, src/test/java/com/lpvs/config/SecurityConfigTest.java, src/test/java/com/lpvs/controller/GitHubControllerTest.java, src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java, src/test/java/com/lpvs/service/LPVSLicenseServiceTest.java, src/test/java/com/lpvs/util/LPVSWebhookUtilTestFuzzer.java
Spring 2.7 has been replaced with 3.2.
Fixes #351
All previous tests that used to work with Spring 2.7 are operating well with Spring 3.2 as well.
=> chore: Switch from Spring 2.7 to 3.2

.clusterfuzzlite/build.sh, .github/PULL_REQUEST_TEMPLATE.md
Spring 2.7 has been replaced with 3.2, therefore we update the fuzzer as well.
* Java: v17
* LPVS Release: v1.4.x
=> fix: Update JDK11 to JDK17 in Fuzzer

.github/workflows/codeql.yml
=> ci: Test java-kotlin for codeql analysis

src/main/resources/application.properties
Code refactoring - removing unused props in `application.properties` file.
=> refactor: Remove unused properties from `application.properties` file

frontend/package-lock.json
Fix `package-lock.json` with incorrect dependency to prevent package publish error.
=> fix: Fix package-lock dependencies

pom.xml, src/main/java/com/lpvs/service/LPVSDetectService.java, src/main/resources/application.properties
Minor changes to user notification during LPVS boot (wrong info that single scan triggered);
removed deprecated mysql dialect in order to remove warnings during boot;
removed unused maven dependency;
* Java: v17
=> chore: remove unused  dependencies

.github/workflows/build.yml, .github/workflows/check-docker.yml, .github/workflows/findbugs.yml, .github/workflows/java-format-checker.yml, .github/workflows/publish-release.yml, .github/workflows/scorecards.yml, .github/workflows/test-suite.yml
Update version of actions/checkout.
Dependabot getting the next error while trying to update actions/checkout: 
```
Error processing actions/checkout (Dependabot::SharedHelpers::HelperSubprocessFailed)
error: no such commit d0651293c4a5a52e711f25b41b05b2212f385d28
```
These changes fix incorrect commits and update all uses of the _checkout_ action to the latest version - 4.1.1
=> ci: fix and update actions/checkout version

src/main/java/com/lpvs/LicensePreValidationSystem.java, src/main/java/com/lpvs/service/LPVSQueueService.java, src/main/java/com/lpvs/util/LPVSCommentUtil.java, src/test/java/com/lpvs/LicensePreValidationSystemTest.java, src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java, src/test/java/com/lpvs/util/LPVSCommentUtilTest.java
The queue needs to be cleared before adding new elements.
* Java: v17
=> fix: Clear the queue before adding new elements

pom.xml
Make standalone jar
fix: update pom.xml
This addition help to create standalone jar- it is very important for using on servers that do not have access to Internet.
Before change needed to add in container dependencies to run jar on remote server.
* Java: v17
* Tested on server
* allowed to run standalone jar in container
=> build: update pom.xml

src/main/java/com/lpvs/service/LPVSQueueService.java
Fix for the incorrect increment of attempts number in case of some fail during webhook processing.
* Java: v17
=> fix: Fix for incorrect increment of the attempts number

doc/quick-start-guide-and-build.md, src/main/resources/application.properties
Improvement of `application.properties` file and corresponding documentation.
=> docs: Update properties and corresponding documentation

src/main/java/com/lpvs/config/SecurityConfig.java, src/main/java/com/lpvs/repository/LPVSPullRequestRepository.java, src/main/java/com/lpvs/service/LPVSQueueService.java, src/main/resources/database_dump.sql
I found that in case the scan fails, LPVS saves pull request information into the table `pull_requests` for each failed attempt. 
This is incorrect behavior. Only one record should be saved for every webhook request.
Also fixed runtime issue with missing ClientRegistrationRepository bean.
* Java: v17
=> fix: Fix the issue with duplicated records in pull_requests table and runtime error (missing bean)

src/main/java/com/lpvs/repository/LPVSLicenseRepository.java, src/main/java/com/lpvs/service/LPVSGitHubService.java, src/main/java/com/lpvs/service/LPVSQueueService.java, src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java, src/test/java/com/lpvs/service/LPVSQueueServiceTest.java
Remove incorrect code from GitHub service and update UTs.
* Java: v17
* LPVS Release: v1.4.2
=> fix: Remove unnecessary try/catch section from the service

src/main/java/com/lpvs/entity/LPVSDetectedLicense.java, src/main/java/com/lpvs/entity/LPVSLicense.java, src/main/java/com/lpvs/entity/LPVSLicenseConflict.java, src/main/java/com/lpvs/entity/LPVSPullRequest.java, src/main/java/com/lpvs/entity/LPVSQueue.java, src/main/java/com/lpvs/entity/auth/LPVSMember.java, src/main/java/com/lpvs/service/LPVSDetectService.java, src/main/java/com/lpvs/service/LPVSLicenseService.java, src/main/resources/application-singlescan.properties, src/main/resources/application.properties, src/test/java/com/lpvs/service/LPVSDetectServiceTest.java, src/test/java/com/lpvs/service/LPVSLicenseServiceTest.java
1. add loading diff before analyzing files for single scan;
2. add manual database init before using;
=> fix: modify single scan feature

.github/workflows/publish-release.yml, pom.xml, src/main/java/com/lpvs/controller/LPVSWebController.java, src/main/java/com/lpvs/service/LPVSStatisticsService.java
During the release v1.4.2 we found that Javadoc can't be generated correctly.
This PR fixes the issue with Javadoc generation. 
=> fix: Fix Javadoc generation

src/main/java/com/lpvs/controller/GitHubController.java, src/main/java/com/lpvs/service/LPVSGitHubService.java, src/main/java/com/lpvs/service/LPVSStatisticsService.java, src/main/java/com/lpvs/service/scanner/scanoss/LPVSScanossDetectService.java, src/main/java/com/lpvs/util/LPVSCommentUtil.java
Fix the issues found after the code scanning by the quality analyzer.
=> fix: Fix issues detected by Svace code analyzer

src/main/java/com/lpvs/service/LPVSLicenseService.java
PR contains a change that is required for the correct operation of dependent modules.
=> refactor: Change visibility of constructor for testability

src/main/java/com/lpvs/service/LPVSQueueService.java, src/main/java/com/lpvs/service/scan/LPVSDetectService.java, src/main/java/com/lpvs/service/scan/LPVSScanService.java, src/main/java/com/lpvs/service/scan/LPVSScanServiceFactory.java, src/main/java/com/lpvs/service/scan/package-info.java, src/main/java/com/lpvs/service/scan/scanner/LPVSScanossDetectService.java, src/main/java/com/lpvs/service/scan/scanner/package-info.java, src/test/java/com/lpvs/service/LPVSDetectServiceTest.java, src/test/java/com/lpvs/service/LPVSQueueServiceTest.java, src/test/java/com/lpvs/service/scan/LPVSDetectServiceTest.java, src/test/java/com/lpvs/service/scan/LPVSScanServiceFactoryTest.java, src/test/java/com/lpvs/service/scan/scanner/LPVSScanossDetectServiceTest.java
Load scan services dynamically based on configuration properties.
The proposed approach provides flexibility for loading different scanners without changes in the source code.
* Java: v17
* LPVS Release: v1.4.2
=> feat: Load scan services dynamically based on configuration properties

doc/quick-start-guide-and-build.md
Incorrect links that can lead to difficulties in setting up the LPVS correctly
=> chore: Fix links in the quick-start-guide-and-build.md

src/main/java/com/lpvs/service/LPVSGitHubService.java, src/main/java/com/lpvs/service/LPVSLicenseService.java, src/main/java/com/lpvs/service/LPVSQueueService.java, src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java, src/test/java/com/lpvs/service/LPVSQueueServiceTest.java
PR contains a fix for the issue Redundant nullcheck of repoLicense.
Also, after modification of the main code, unit tests were updated as well.
* Java: v17
* LPVS Release: v1.5.0
=> fix: Fix svace issue Redundant null check

src/main/java/com/lpvs/LicensePreValidationService.java, src/main/java/com/lpvs/service/LPVSGitHubService.java, src/main/java/com/lpvs/service/scan/LPVSDetectService.java, src/main/java/com/lpvs/service/scan/scanner/LPVSScanossDetectService.java, src/test/java/com/lpvs/service/scan/LPVSDetectServiceTest.java, src/test/java/com/lpvs/service/scan/scanner/LPVSScanossDetectServiceTest.java, src/test/java/com/lpvs/util/LPVSCommentUtilTest.java
PR contains some modification of log messages related to single scan (CLI) operation. Also, provided correct exception handling in case of app closing. 
Fixes #512
Testing is performed for current PR.
* Java: v17
* LPVS Release: v1.5.0
=> fix: Fix logs and exceptions handling for single scan mode

src/main/java/com/lpvs/controller/LPVSWebController.java, src/main/java/com/lpvs/service/LPVSLoginCheckService.java, src/test/java/com/lpvs/controller/GitHubControllerTest.java, src/test/java/com/lpvs/service/LPVSLicenseServiceTest.java
- Modify LoginCheck to remove unnecessary function;
- refactor unit tests for LicenseService, improving coverage;
* Java: v17
=> refactor: Refactor LoginCheck and existing unit test for License Service

src/main/java/com/lpvs/service/scan/scanner/LPVSScanossDetectService.java, src/test/java/com/lpvs/service/scan/scanner/LPVSScanossDetectServiceTest.java
The `checkLicenses` has been refactored due to long method.
The unit tests, `testWithNullHeadCommitSHA` and `testWithNullHeadCommitSHADB`, have been fixed to read the existing test file.
This PR was verified by the unit test.
* Java: v17
=> refactor: LPVSScanossDetectService refactoring and unit test fix

src/main/java/com/lpvs/service/scan/scanner/LPVSScanossDetectService.java, src/main/java/com/lpvs/util/LPVSFileUtil.java, src/test/java/com/lpvs/util/LPVSFileUtilTest.java
It's refactored to use LPVSFileUtil API. 
Unit tests of LPVSFileUtil have been updated to use `assertEquals` to improve accuracy.
This PR is verified by the unit tests.
* Java: v17
=> refactor: Use LPVSFileUtil API for getReader

doc/quick-start-guide-and-build.md, src/main/java/com/lpvs/entity/LPVSDetectedLicense.java, src/main/java/com/lpvs/entity/LPVSLicense.java, src/main/java/com/lpvs/entity/LPVSLicenseConflict.java, src/main/java/com/lpvs/entity/LPVSPullRequest.java, src/main/java/com/lpvs/entity/LPVSQueue.java, src/main/java/com/lpvs/entity/auth/LPVSMember.java, src/main/java/com/lpvs/repository/LPVSLicenseConflictRepository.java, src/main/java/com/lpvs/repository/LPVSLicenseRepository.java, src/main/java/com/lpvs/repository/LPVSPullRequestRepository.java, src/main/java/com/lpvs/repository/LPVSQueueRepository.java, src/main/java/com/lpvs/service/LPVSLicenseService.java, src/main/java/com/lpvs/util/LPVSPayloadUtil.java, src/main/resources/database_dump.sql, src/test/java/com/lpvs/entity/LPVSPullRequestTest.java, src/test/java/com/lpvs/util/LPVSPayloadUtilTest.java
PR contains the next changes:
- renamed tables (added "lpvs_" prefix)
- native queries replaced with non-native queries (to avoid modification of queries in case of tables renaming)
- unit tests updated
- documentation update (fixed names of tables)
Verified on PR: https://github.sec.samsung.net/SOSHUB/LPVS-test/pull/1543#issuecomment-2729707
=> refactor: Change table names, replace native queries with a non-native

src/main/java/com/lpvs/controller/LPVSWebController.java, src/main/java/com/lpvs/repository/LPVSDetectedLicenseRepository.java, src/main/java/com/lpvs/repository/LPVSLicenseConflictRepository.java, src/main/java/com/lpvs/repository/LPVSLicenseRepository.java, src/main/java/com/lpvs/repository/LPVSPullRequestRepository.java, src/main/java/com/lpvs/repository/LPVSQueueRepository.java, src/main/java/com/lpvs/service/LPVSGitHubService.java, src/main/java/com/lpvs/service/LPVSLicenseService.java, src/main/java/com/lpvs/service/LPVSLoginCheckService.java, src/main/java/com/lpvs/service/LPVSQueueService.java, src/main/java/com/lpvs/service/LPVSStatisticsService.java, src/test/java/com/lpvs/controller/LPVSWebControllerTest.java, src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java, src/test/java/com/lpvs/service/LPVSLicenseServiceTest.java, src/test/java/com/lpvs/service/LPVSQueueServiceTest.java, src/test/java/com/lpvs/service/LPVSStatisticsServiceTest.java
Current PR contains refactoring of the repository method names to enable name-based query derivation.
This change was proposed [here](https://github.com/Samsung/LPVS/pull/537#discussion_r1644036139).
Because I'm not an expert in name-based queries, I would be grateful for the careful code review.
Also, functional test run is required for this PR.
Unit tests - passed.
=> refactor: Rename repository methods for name-based query derivation

src/main/java/com/lpvs/LicensePreValidationService.java, src/test/java/com/lpvs/LicensePreValidationServiceTest.java
The current PR adds the feature to show the LPVS logo at the start of the app. Besides that, it contains the app's version number. I tried to take the number from the POM file but failed to do this at the app start - I was successful in getting the version when all was already loaded, but we need it at the app launching time. So, the version number was hardcoded near the logo.
=> feat: Show LPVS logo at the app start

src/main/java/com/lpvs/util/LPVSFileUtil.java
Fix for the Svace issue with ignored check for `mkdir()`
=> fix: Fix Svace issue with ignored check

pom.xml, src/main/java/com/lpvs/LicensePreValidationService.java, src/main/resources/application.properties, src/test/java/com/lpvs/LicensePreValidationServiceTest.java
Current PR includes changes in how to get the LPVS application's current version.
The proposed approach doesn't need to add any dependency. It uses only `application.properties` and POM files of the project. 
Because of changes in application start, unit tests were also modified and updated.
By using unit tests and application start.
=> refactor: Taking the LPVS version from the POM file

src/main/java/com/lpvs/entity/LPVSFile.java, src/main/java/com/lpvs/entity/report/LPVSReportBuilder.java, src/main/java/com/lpvs/service/LPVSGitHubService.java, src/main/java/com/lpvs/service/scan/LPVSDetectService.java, src/main/java/com/lpvs/util/LPVSCommentUtil.java, src/test/java/com/lpvs/entity/LPVSFileTest.java, src/test/java/com/lpvs/entity/report/LPVSReportBuilderTest.java, src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java, src/test/java/com/lpvs/service/scan/LPVSDetectServiceTest.java, src/test/java/com/lpvs/util/LPVSCommentUtilTest.java
Current PR contains an updated, user-friendly version of the command line report for single scans (PR or local files).
Tested locally for PR and local file scan.
=> feat: User friendly command line report for single scan

src/main/java/com/lpvs/entity/report/LPVSReportBuilder.java, src/main/java/com/lpvs/service/LPVSGitHubService.java, src/main/resources/templates/report_single_scan.html, src/test/java/com/lpvs/entity/report/LPVSReportBuilderTest.java, src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java
The current PR contains significant updates on the pull request comments. 
Changes cover HTML and MD comment formats.
Tested on the local environment.
Test PR: https://github.com/o-kopysov/LPVS/pull/2
Short view:
Full view:
=> feat: Implement updated pull request comments (HTML and MD)

src/main/java/com/lpvs/config/SecurityConfig.java, src/main/java/com/lpvs/entity/report/LPVSReportBuilder.java, src/test/java/com/lpvs/LicensePreValidationServiceTest.java, src/test/java/com/lpvs/service/OAuthServiceTest.java
Removed all warnings during the build process.
Currently have 0 build warnings.
Local command line build.
=> fix: Warning messages removal during the build process

doc/docs/user-guide/service/database.md, doc/docs/user-guide/service/webhook.md, doc/lpvs-api.yaml, src/main/java/com/lpvs/controller/GitHubController.java, src/test/java/com/lpvs/controller/GitHubControllerTest.java
In order to simplify setup for end user, default endpoint that forward requests added. Now user just need to paste LPVS URL in github webhooks without adding '/webhooks' endpoint. 
Corresponding guide updated.
* Java: v17
=> feat: Add default endpoint that forward POST requests to /webhooks

.clusterfuzzlite/Dockerfile
The new docker container supports the build using java 17. Therefore, the Fuzzer can be successfully launched.
Fixes #405
* Java: v17
* LPVS Release: v1.5.2
=> fix: Update the clusterfuzzlite docker container

src/main/java/com/lpvs/entity/LPVSConflict.java, src/main/java/com/lpvs/entity/report/LPVSReportBuilder.java, src/main/java/com/lpvs/service/LPVSGitHubService.java, src/main/java/com/lpvs/service/LPVSLicenseService.java, src/main/java/com/lpvs/service/scan/LPVSDetectService.java, src/main/java/com/lpvs/service/webhook/LPVSWebhookServiceImpl.java, src/test/java/com/lpvs/entity/LPVSConflictTest.java, src/test/java/com/lpvs/entity/report/LPVSReportBuilderTest.java, src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java, src/test/java/com/lpvs/service/LPVSLicenseServiceTest.java, src/test/java/com/lpvs/service/scan/LPVSDetectServiceTest.java
Currently, the source code has several MCD (Module Circular Dependency) that can be fixed to improve the overall LPVS architecture. 
Current PR contains the refactoring the code to separate `LPVSConflict` to the independent class.
Tested using unit tests.
=> refactor: improve MCD (Module Circular Dependency) metric of the code

src/main/java/com/lpvs/service/LPVSGitHubService.java, src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java
Added the link to the hub link (when available) at the end of the pull request message. 
Tested locally using unit tests.
=> feat: Display link to the hub in pull request message when available

src/main/java/com/lpvs/util/LPVSFileUtil.java
Current PR contains a bug fix for the incorrect conversion to string when the queue element equals null.
Checked by functional tests.
=> fix: Incorrect conversion to string when equals to null

doc/docs/dev-guide/faq.md, doc/mkdocs.yml
Add to the FAQ page of the project documentation guide to generate Python requirements with hashes
=> docs: Update FAQ page with generation Python requirements guide

src/main/java/com/lpvs/service/LPVSGitHubService.java, src/main/java/com/lpvs/service/webhook/LPVSWebhookServiceImpl.java, src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java, src/test/java/com/lpvs/service/webhook/LPVSWebhookServiceImplTest.java
The current pull request improves the way to take the license of the repository from GitHub (using SPDX ID, not a license key as previously). This change is related to the upgrade of the GitHub library #631 .
Checked locally.
=> fix: Take SPDX ID from GitHub API when searching for the license

src/main/java/com/lpvs/service/LPVSGitHubConnectionService.java
Fix for the single scan of local files - stop asking GH token.
Checked locally.
=> fix: Skip asking GH token for local scans

doc/docs/user-guide/cli/cli_file.md, doc/docs/user-guide/cli/cli_pr.md, doc/docs/user-guide/config/options.md, pom.xml, src/main/java/com/lpvs/entity/report/LPVSReportBuilder.java, src/main/java/com/lpvs/service/scan/LPVSDetectService.java, src/main/resources/templates/report_single_scan.html, src/test/java/com/lpvs/entity/report/LPVSReportBuilderTest.java, src/test/java/com/lpvs/service/LPVSGitHubServiceTest.java, src/test/java/com/lpvs/service/scan/LPVSDetectServiceTest.java
Added feature for generation of the single scan reports in PDF format.
Unit tests, documentation, and the report template are fixed as well.
Tested locally.
@tdrozdovsky - Functional tests update is required as well.
=> feat: Generate PDF report for single scan mode

README.md
Remove unactual badges:
- build: non-significant badge. 
- doi: stopped to work properly - I can't upload new releases on zenodo website because of space limitation. 
=> docs: Remove unactual badges from readme

src/main/java/com/lpvs/controller/GitHubController.java, src/main/java/com/lpvs/entity/enums/LPVSPullRequestAction.java, src/main/java/com/lpvs/service/LPVSGitHubConnectionService.java, src/test/java/com/lpvs/entity/enums/LPVSPullRequestActionTest.java
Introduced alternative function for communicating with GitHub API using token.
Added unit tests where possible.
Local run of unit tests.
=> chore: Extend the list of possible connections to GitHub

src/main/java/com/lpvs/util/LPVSCommentUtil.java, src/main/java/com/lpvs/util/LPVSFileUtil.java, src/main/java/com/lpvs/util/LPVSPayloadUtil.java, src/test/java/com/lpvs/service/scan/LPVSDetectServiceTest.java, src/test/java/com/lpvs/util/LPVSCommentUtilTest.java, src/test/java/com/lpvs/util/LPVSFileUtilTest.java, src/test/java/com/lpvs/util/LPVSPayloadUtilTest.java
The file-saving function is divided into 2 parts for better maintenance.
Added unit tests to cover more branches.
Local run of UTs.
=> refactor: Divide file save function into 2 parts, add UTs

src/main/java/com/lpvs/service/webhook/LPVSWebhookServiceImpl.java, src/test/java/com/lpvs/service/webhook/LPVSWebhookServiceImplTest.java, src/test/java/com/lpvs/util/LPVSPayloadUtilTest.java
Current PR contains small fixes in the source code and adds new unit tests for functions that are not covered by unit tests.
Local run.
=> test: Add unit tests for uncovered function

src/main/java/com/lpvs/util/LPVSPayloadUtil.java
Current PR adds a check if 'acttion' field is present in the payload.
=> fix: Add missing check for payload

doc/requirements-docs.txt
Fixed conflicting versions of dependencies for generating docs.
```
ERROR: Cannot install -r doc/requirements-docs.txt (line 150) and h11==0.16.0 because these package versions have conflicting dependencies.
The conflict is caused by:
The user requested h11==0.16.0
httpcore 1.0.7 depends on h11<0.15 and >=0.13
```
```
pip install --require-hashes -r doc/requirements-docs.txt
```
=> fix: Fix conflicting versions
